dbDriverClass: com.mysql.jdbc.Driver
dbUrl: jdbc:mysql://localhost:3306/my_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
dbUsername: root
dbPassword: njutzjz126
projectName: test
packageName: com.github.zjzcn.test