dbDriverClass: com.mysql.jdbc.Driver
dbUrl: jdbc:mysql://localhost:3306/bookcase?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
dbUsername: root
dbPassword: njutzjz126
projectName: bookcase
systemName: 机器人后台
packageName: com.planetengine.bookcase