dbDriverClass: com.mysql.jdbc.Driver
dbUrl: jdbc:mysql://localhost:3306/ai_studio?characterEncoding=utf8&useSSL=false
dbUsername: root
dbPassword: njutzjz126
projectName: test
systemName: 测试系统
packageName: com.test.system

unusedTables: []
createTimeColumn: created_at
updateTimeColumn: updated_at
deletedColumn: deleted
enabledColumn: enabled